### ISSUE TITLE
Command Change: add-file and add-git split into shared command namespace

### ISSUE THREAD

**Issue by SimplicityGuy** [ssagar0/zoom#1]
Currently there are 2 commands: `add-file` and `add-git`. Consider switching over to a generic `add` command that will list all the providers there. So `zoom add-file foo.txt` changes to `zoom add file foo.txt` and similarly for `add-git`.

**Comment by ssagar0** [comment]
I actually originally went in this direction. I backed that out once I started designing the full command set I wanted for zoom's first non-beta release. In order to make a zoom project feel more like a cohesive git repo there are certain git commands (such as `git add`) that I want to mimic. Since this is still in beta, the `add-git` and `add-file` commands are subject to change but I can almost certainly say they won't be changed to `add git` and `add file`. If you have a different suggestion for those commands I'm happy to hear it.

**Comment by SimplicityGuy** [comment]
Agreed.  How about `include file` instead of `add-file`? etc.

**Comment by ssagar0** [comment]
An `include` command sounds good to me. I'm planning on cutting a new release by the end of the week so I'll try to get this change in by then.

**Comment by ssagar0** [comment]
0.0.14 has switched `add-git` and `add-file` to `include git` and `include file`.
